// src/utils/helpers/index.js

// Exportar helpers de fechas
export {
  formatDate,
  formatDateTime,
  formatTime,
  formatDateTime12h,
  formatRelativeDate,
  formatTimeDistance,
  formatSmartDate,
  formatChatDate,
  getCurrentTimestamp,
  getCurrentISODate,
  isTodayDate,
  isYesterdayDate,
  getDaysDifference,
  getHoursDifference,
  getMinutesDifference,
  isValidDate,
  parseDate,
  addDays,
  subtractDays,
  getStartOfDay,
  getEndOfDay,
} from './dateHelpers';

// Exportar helpers de strings
export {
  capitalize,
  capitalizeWords,
  toUpperCase,
  toLowerCase,
  truncate,
  truncateWords,
  slugify,
  generateId,
  generateUUID,
  getInitials,
  cleanSpaces,
  removeAccents,
  countWords,
  countCharacters,
  isEmpty,
  isNumeric,
  isAlpha,
  isAlphanumeric,
  escapeHtml,
  unescapeHtml,
  extractNumbers,
  extractLetters,
  formatPhoneNumber,
  formatFullName,
  abbreviateName,
  maskString,
  maskEmail,
  pluralize,
  randomString,
  normalizeSpaces,
  removeSpecialChars,
} from './stringHelpers';

// Exportar helpers de formato
export {
  formatNumber,
  formatCurrency,
  formatCurrencyCompact,
  formatPercentage,
  formatBytes,
  formatNumberCompact,
  formatDuration,
  formatDurationMs,
  formatCoordinates,
  formatList,
  formatPhone,
  formatCreditCard,
  maskCreditCard,
  formatRFC,
  formatCURP,
  formatPostalCode,
  formatDistance,
  formatSpeed,
  formatTemperature,
  formatWeight,
  formatRating,
  formatStarRating,
  formatVersion,
  formatShortHash,
  formatShortUUID,
  formatJSON,
  formatBoolean,
  formatArray,
  formatOrdinal,
} from './formatHelpers';

// Exportar helpers de storage
export {
  isStorageAvailable,
  setStorage,
  getStorage,
  removeStorage,
  clearStorage,
  clearStorageByPrefix,
  hasStorage,
  getStorageKeys,
  getStorageSize,
  setStorageWithExpiry,
  getStorageWithExpiry,
  cleanExpiredStorage,
  setMultipleStorage,
  getMultipleStorage,
  exportStorage,
  importStorage,
  setSessionStorage,
  getSessionStorage,
  removeSessionStorage,
  clearSessionStorage,
} from './storageHelpers';

// Exportar modulos completos como namespace
export * as dateHelpers from './dateHelpers';
export * as stringHelpers from './stringHelpers';
export * as formatHelpers from './formatHelpers';
export * as storageHelpers from './storageHelpers';